namespace TeamsMediaBot.Models
{
    /// <summary>
    /// Request payload sent to Ktor to initialize a bot session for an incoming call.
    /// </summary>
    public record KtorSessionInitRequest
    {
        /// <summary>
        /// The Teams thread ID from the meeting.
        /// </summary>
        public required string ThreadId { get; init; }

        /// <summary>
        /// The Teams message ID from the meeting.
        /// </summary>
        public required string MessageId { get; init; }

        /// <summary>
        /// The Azure AD tenant ID.
        /// </summary>
        public required string TenantId { get; init; }

        /// <summary>
        /// The Teams meeting ID.
        /// </summary>
        public required string MeetingId { get; init; }
    }

    /// <summary>
    /// Response from Ktor after initializing a bot session.
    /// Contains the session ID and a URL to send to the meeting chat.
    /// </summary>
    public record KtorSessionInitResponse
    {
        /// <summary>
        /// The session ID to use for WebSocket connection and tracking.
        /// </summary>
        public required string SessionId { get; init; }

        /// <summary>
        /// The URL to send to the meeting chat for participants.
        /// </summary>
        public required string Url { get; init; }
    }

    /// <summary>
    /// Transcript payload sent to Ktor via WebSocket.
    /// </summary>
    public record TranscriptMessage
    {
        /// <summary>
        /// Message type identifier.
        /// </summary>
        public string Type { get; init; } = "TRANSCRIPT";

        /// <summary>
        /// The session ID this transcript belongs to.
        /// </summary>
        public required string SessionId { get; init; }

        /// <summary>
        /// The transcribed text from Deepgram.
        /// </summary>
        public required string Text { get; init; }

        /// <summary>
        /// Indicates if this is a final transcript (true) or interim (false).
        /// </summary>
        public required bool IsFinal { get; init; }
    }

    /// <summary>
    /// Meeting end notification sent to Ktor via WebSocket.
    /// </summary>
    public record MeetingEndMessage
    {
        /// <summary>
        /// Message type identifier.
        /// </summary>
        public string Type { get; init; } = "MEETING_END";

        /// <summary>
        /// The session ID of the meeting that ended.
        /// </summary>
        public required string SessionId { get; init; }

        /// <summary>
        /// Reason for meeting end (e.g., "MEETING_ENDED", "ERROR").
        /// </summary>
        public required string Reason { get; init; }
    }

    /// <summary>
    /// Live summary message received from Ktor via WebSocket.
    /// </summary>
    public record LiveSummaryMessage
    {
        /// <summary>
        /// Message type identifier.
        /// </summary>
        public string Type { get; init; } = "LIVE_SUMMARY";

        /// <summary>
        /// The session ID this summary belongs to.
        /// </summary>
        public string? SessionId { get; init; }

        /// <summary>
        /// The summary text generated by Ktor.
        /// </summary>
        public string? Summary { get; init; }
    }

}
